import type { ThemeConfig } from "../types";
import { DEFAULT_THEME } from "../constants";

export function resolveTheme(overrides?: ThemeConfig): Required<ThemeConfig> {
  return { ...DEFAULT_THEME, ...overrides };
}

export function cssVars(theme: Required<ThemeConfig>): React.CSSProperties {
  return {
    "--ls-primary": theme.primaryColor,
    "--ls-secondary": theme.secondaryColor,
    "--ls-bg": theme.backgroundColor,
    "--ls-text": theme.textColor,
    "--ls-radius": `${theme.borderRadius}px`,
    "--ls-font": theme.fontFamily,
  } as React.CSSProperties;
}

/* Shared inline style objects — no external CSS dependency */
export const styles = {
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 9999,
    fontFamily: "var(--ls-font)",
    color: "var(--ls-text)",
  },
  modal: {
    background: "var(--ls-bg)",
    borderRadius: "var(--ls-radius) var(--ls-radius) 0 0",
    width: "100%",
    maxWidth: 480,
    maxHeight: "92vh",
    overflow: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    position: "relative" as const,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    borderBottom: "1px solid #f0f0f0",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  logo: {
    width: 32,
    height: 32,
    borderRadius: 8,
    objectFit: "cover" as const,
  },
  stepTitle: {
    fontWeight: 700,
    fontSize: 18,
  },
  closeBtn: {
    background: "none",
    border: "none",
    fontSize: 24,
    cursor: "pointer",
    color: "var(--ls-text)",
    padding: 4,
    lineHeight: 1,
  },
  backBtn: {
    background: "none",
    border: "1px solid #ddd",
    borderRadius: "50%",
    width: 32,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 16,
  },
  body: {
    flex: 1,
    padding: "20px 20px 24px",
    overflow: "auto" as const,
  },
  footer: {
    padding: "16px 20px 32px",
    borderTop: "1px solid #f0f0f0",
  },
  primaryBtn: {
    width: "100%",
    padding: "14px 0",
    border: "none",
    borderRadius: 999,
    background: "linear-gradient(135deg, var(--ls-primary), var(--ls-secondary))",
    color: "#fff",
    fontWeight: 600,
    fontSize: 16,
    cursor: "pointer",
    transition: "opacity 0.2s",
  },
  primaryBtnDisabled: {
    opacity: 0.4,
    cursor: "not-allowed" as const,
  },
  secondaryBtn: {
    width: "100%",
    padding: "14px 0",
    border: "1px solid #ddd",
    borderRadius: 999,
    background: "#fff",
    color: "var(--ls-text)",
    fontWeight: 600,
    fontSize: 16,
    cursor: "pointer",
  },
  input: {
    width: "100%",
    padding: "12px 0",
    border: "none",
    borderBottom: "1px solid #e0e0e0",
    fontSize: 15,
    outline: "none",
    background: "transparent",
    color: "var(--ls-text)",
    fontFamily: "inherit",
  },
  label: {
    fontSize: 14,
    fontWeight: 500,
    color: "#666",
    marginBottom: 4,
  },
  fieldRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 0",
    borderBottom: "1px solid #f0f0f0",
    cursor: "pointer",
  },
  fieldLabel: {
    fontSize: 15,
    fontWeight: 500,
  },
  fieldValue: {
    fontSize: 15,
    color: "#999",
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  fieldValueFilled: {
    fontSize: 15,
    color: "var(--ls-text, #222)",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  errorBanner: {
    background: "#FFF0F0",
    color: "#D32F2F",
    padding: "10px 16px",
    borderRadius: 8,
    fontSize: 14,
    marginBottom: 16,
  },
  lineConnected: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#E8F5E9",
    borderRadius: 12,
    padding: "12px 16px",
    marginBottom: 20,
  },
  lineAvatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    objectFit: "cover" as const,
  },
  lineName: {
    flex: 1,
    fontWeight: 600,
    fontSize: 15,
  },
  lineStatus: {
    color: "#4CAF50",
    fontSize: 13,
    fontWeight: 500,
  },
  lineBadge: {
    width: 32,
    height: 32,
  },
  incentiveBanner: {
    background: "#E0F7FA",
    borderRadius: 8,
    padding: "10px 16px",
    textAlign: "center" as const,
    fontSize: 14,
    fontWeight: 500,
    marginTop: 16,
  },
  personaGrid: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 20,
    justifyContent: "center",
    padding: "20px 0",
  },
  personaCard: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    position: "relative" as const,
    width: 100,
  },
  personaImg: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    objectFit: "cover" as const,
    border: "3px solid transparent",
    transition: "border-color 0.2s",
  },
  personaImgSelected: {
    borderColor: "var(--ls-primary)",
  },
  personaCheck: {
    position: "absolute" as const,
    top: 0,
    right: 10,
    width: 22,
    height: 22,
    borderRadius: "50%",
    background: "#4CAF50",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
  },
  personaName: {
    fontSize: 13,
    textAlign: "center" as const,
    fontWeight: 500,
  },
  consentBody: {
    fontSize: 14,
    lineHeight: 1.7,
    color: "#555",
    maxHeight: 300,
    overflow: "auto" as const,
    padding: "16px 0",
  },
  consentActions: {
    display: "flex",
    gap: 12,
    marginTop: 16,
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 0",
    cursor: "pointer",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    border: "2px solid #ddd",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "all 0.15s",
  },
  checkboxChecked: {
    background: "var(--ls-primary)",
    borderColor: "var(--ls-primary)",
    color: "#fff",
  },
  spinner: {
    width: 20,
    height: 20,
    border: "2px solid #fff",
    borderTopColor: "transparent",
    borderRadius: "50%",
    animation: "ls-spin 0.6s linear infinite",
    display: "inline-block",
  },
};
